import {
FETCH_USER_SUCCESS,
FETCH_USER_ERROR,
ADD_PROFILE,
ADD_PROFILE_SUCCESS,
ADD_PROFILE_ERROR,
EDIT_PROFILE,
EDIT_PROFILE_SUCCESS,
EDIT_PROFILE_ERROR,
DELETE_PROFILE,
DELETE_PROFILE_SUCCESS,
DELETE_PROFILE_ERROR,

//LIST ALL USERS
FETCH_USERS_START,
FETCH_USERS_SUCCESS,
FETCH_USERS_ERROR,

FETCH_TRIP_START,
FETCH_TRIP_SUCCESS,
FETCH_TRIP_ERROR,
ADD_TRIP,
ADD_TRIP_SUCCESS,
ADD_TRIP_ERROR,
EDIT_TRIP,
EDIT_TRIP_SUCCESS,
EDIT_TRIP_ERROR,
DELETE_TRIP,
DELETE_TRIP_SUCCESS,
DELETE_TRIP_ERROR
} from '../actions';

const intitalState = {
     
}